dist: trusty
language: node_js
node_js: v10
install:
- npm i
deploy:
  provider: npm
  email: smilingxinyi@gmail.com
  api_key:
    secure: "BTa6IZ3l3i6z6kySfgp7rP6mooeYRajmEdTQG5OjLKh1pwLf7N/dpn6F/ZoAiarqVM39mMUMwC3bsNLGrLq/4oHGmS7m9ukgNsw1VI9RZlUAOs591cCP14Fp+MmYsPZnzgTBJ3TRTx9OLYGXWTxkK3+l13ayRz96VyyszcwSBhIe5QNm3FZ/prUCUGsDNAz4ObIOEjzs9SQU1Hx0Oc4x6qSIctgMox5JgY86IgHiK/mq4Kin+FL8JYbWW/Hg+laxiFSHq89hGYQBd+nNCXXdviuGNhxAMJxvytZES9m0Hqv+T9s1oGHu1NeXLCijEa8D2L6vbcHqFzaClbzNtyPJrLrdLM3x4MoSMxR9+wIOg93xeIx6/eXB/rn0SC8he5uoDLuLDmFux2MYiiOjw11caurP2x+WWgfZhF6NyOtDCwoQnIVB8sfKt4//aoXimkBjz47/76eHhD6i+i4Ko2ieSqoooJ4moaADtm38dQOvHqUFQs8JdXXqlqq0GEmuPsQ0i23PCm4CuOV35J8jsRA2PeghHVRgfUW6DMbRS7247n6KIR8JNASOILlGGqt74whB9AGkjvMn+cK8UFqjWBH5J3uDoZrsHWqib8iqhT6SLC1hdxX/Gdr5RsG8zzy7esuAvQVp28ASYkQW/Tqyp/PRC1THd9S0YblVSGIxAwzKWnI="
  on:
    tags: true
    repo: "misaka-ink/require2"